Makedata and Checkdata for analyzers tab
arangodb/release-test-automation pull request #257
Opened 2022-05-24 06:32 UTC by MDAlFattah

2022-05-24 07:20 UTC, dothebart commented on test_data/makedata_suites/600_analyzers.js
> +        a.remove("trigram");
fix the name pls.

2022-05-24 07:23 UTC, dothebart commented on test_data/makedata_suites/600_analyzers.js
> +      if (a.toArray().length !== 14) {
search the array for an analyzer of the matching name. 
example code:
```
    return global.theInstanceManager.arangods.filter((instance) => instance.instanceRole === role);
```
(unrelated, just found in cut'n'paste buffer.

2022-05-24 07:26 UTC, dothebart commented
this is a good start!
now we need 
- 1 file with all analyzers available since 3.8
- 1 file (the already added one) filled with all analyzers that became possible with 3.9
- 1 file for devel

2022-05-24 08:42 UTC, MDAlFattah commented on test_data/makedata_suites/600_analyzers.js
> +        a.remove("trigram");
done.

2022-06-02 07:30 UTC, dothebart commented
please add more error handling, as stated. 
please also lint using the arangodb source `./utils/jslint.sh [filename]`; from a first glance tons of `;` are missing - Horay for python ;-)

2022-06-09 08:19 UTC, dothebart requested changes
- make sure you generate the name of the item with the db-counter in all places
- wrap print or delete if toArray() aren't needed
- filter for the analyzer you want to inspect instead of asserting on the total count of analyzers in the db

2022-06-09 08:19 UTC, dothebart commented on test_data/makedata_suites/607_analyzers.js
> +      a.toArray();
wrap with print

2022-06-09 08:19 UTC, dothebart commented on test_data/makedata_suites/607_analyzers.js
> +      if (a.toArray().length !== 14) {
filter for the exact analyzer you're searching for

2022-06-09 08:19 UTC, dothebart commented on test_data/makedata_suites/607_analyzers.js
> +      if (a.analyzer("text_0") == null) {
create string respecting count parameter

2022-06-09 08:19 UTC, dothebart commented on test_data/makedata_suites/607_analyzers.js
> +        if (a.analyzer("text_0") != null) {
generate name

2022-06-09 08:19 UTC, dothebart commented on test_data/makedata_suites/608_analyzers.js
> +      a.toArray();
wrap in print

2022-06-09 08:19 UTC, dothebart commented on test_data/makedata_suites/608_analyzers.js
> +      if (a.analyzer("pipeline_0") == null) {
generate name

2022-06-09 08:19 UTC, dothebart commented on test_data/makedata_suites/608_analyzers.js
> +      let pipelineArray = db._query(`RETURN TOKENS("Quick brown foX", "pipeline_0")`).toArray();
generate name

2022-06-22 13:54 UTC, dothebart commented
https://jenkins01.arangodb.biz/view/Upgrade/job/Upgrade-3.9-to-devel.Linux/425/ launched.

2022-06-22 16:23 UTC, merged